general:
  model_path: C:\Users\Niranjan\Desktop\Modelzoo-project\VISTA\stm32ai-modelzoo-services\image_classification\src\experiments_outputs\2025_07_01_09_40_25\quantized_models\quantized_model.tflite

operation_mode: benchmarking

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

tools:
   stedgeai:
      version: 10.0.0 #10.0.0 #10.0.0
      optimization: balanced
      on_cloud: True
      path_to_stedgeai: C:/Users/Niranjan/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/10.1.0/Utilities/windows/stedgeai.exe

   path_to_cubeIDE: C:/ST/STM32CubeIDE_1.18.1/STM32CubeIDE/stm32cubeide.exe

benchmarking:
   board: STM32H747I-DISCO #STM32N6570-DK #STM32H747I-DISCO

mlflow:
   uri: ./src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}