general:
  model_path: C:\Users\Niranjan\Desktop\Modelzoo-project\VISTA\stm32ai-modelzoo-services\image_classification\src\experiments_outputs\2025_07_01_09_40_25\quantized_models\quantized_model.tflite

operation_mode: evaluation

evaluation:
   target: host # host, stedgeai_host, stedgeai_n6

dataset:
   name: Vegetable_Images
   class_names: [  bitter_gourd, bottle_gourd, brinjal, broccoli, cabbage, capsicum, cauliflower, cucumber, potato, pumpkin, tomato ]                             
   training_path: C:/Users/Niranjan/Desktop/Modelzoo-project/VISTA/stm32ai-modelzoo-services/image_classification/datasets/Vegetable_Images/train
   validation_path: C:/Users/Niranjan/Desktop/Modelzoo-project/VISTA/stm32ai-modelzoo-services/image_classification/datasets/Vegetable_Images/validation
   validation_split: 0.1
   test_path: C:/Users/Niranjan/Desktop/Modelzoo-project/VISTA/stm32ai-modelzoo-services/image_classification/datasets/Vegetable_Images/test
   check_image_files: False

preprocessing:
   rescaling:
      scale: 1/127.5
      offset: -1
   resizing:
      interpolation: bilinear
      aspect_ratio: fit
   color_mode: rgb

mlflow:
   uri: ./src/experiments_outputs/mlruns

hydra:
   run:
      dir: ./src/experiments_outputs/${now:%Y_%m_%d_%H_%M_%S}